import type { QueueItemData } from "$lib/types";
import { urlID as newItemID } from ".";

export const current: QueueItemData = {
	id: newItemID(),
	submittedAt: new Date("10/25/2025"),
	url: "https://itch.io/the-great-escape",
	title: "Three's a Crime",
	by: "Rylydou",
	note: "A must-play indie game with innovative puzzle mechanics.",
	status: "current",
	infoChangedAt: new Date(),
	statusChangedAt: new Date(),
};

export const holdQueue: QueueItemData[] = [
	{
		id: newItemID(),
		submittedAt: new Date("11/15/2025"),
		url: "https://itch.io/dream-diver",
		title: "Dream Diver: Labyrinth of Sleep",
		by: "NightStudio",
		note: "High priority. The developers have a great track record for narrative-focused games.",
		status: "hold",
		infoChangedAt: new Date(),
		statusChangedAt: new Date(),
	},
	{
		id: newItemID(),
		submittedAt: new Date("07/01/2025"),
		url: "https://itch.io/baker-battle",
		title: "The Great Baker Battle",
		by: "OvenMitts",
		note: "Very simple, light-hearted fun.",
		status: "hold",
		infoChangedAt: new Date(),
		statusChangedAt: new Date(),
	},
	{
		id: newItemID(),
		submittedAt: new Date("12/20/2025"),
		url: "https://itch.io/star-ship-builder",
		title: "Star Ship Builder Tycoon",
		by: "CosmicDevs",
		note: "", // Empty note
		status: "hold",
		infoChangedAt: new Date(),
		statusChangedAt: new Date(),
	},
];

export const nextQueue: QueueItemData[] = [
	{
		id: newItemID(),
		submittedAt: new Date("09/15/2025"),
		url: "https://itch.io/pixel-adventure",
		title: "Pixel Adventure RPG",
		by: "GameDevNick",
		note: "Short and sweet.",
		status: "queue",
		infoChangedAt: new Date(),
		statusChangedAt: new Date(),
	},
	{
		id: newItemID(),
		submittedAt: new Date("11/01/2025"),
		url: "https://itch.io/cosmic-drift",
		title: "Cosmic Drift",
		by: "StellarGames",
		note: "", // Empty note
		status: "queue",
		infoChangedAt: new Date(),
		statusChangedAt: new Date(),
	},
	{
		id: newItemID(),
		submittedAt: new Date("10/10/2025"),
		url: "https://itch.io/shadow-runner",
		title: "Shadow Runner 2077",
		by: "NightCrawl",
		note: "Remember to check the system requirements. This one is supposedly a very long and detailed cyberpunk narrative experience with branching paths and multiple endings. Might need a big chunk of dedicated submittedAt.",
		status: "queue",
		infoChangedAt: new Date(),
		statusChangedAt: new Date(),
	},
	{
		id: newItemID(),
		submittedAt: new Date("08/20/2025"),
		url: "https://itch.io/frog-farmer",
		title: "Frog Farmer Sim",
		by: "PondWorks",
		note: "Fun co-op game.",
		status: "queue",
		infoChangedAt: new Date(),
		statusChangedAt: new Date(),
	},
	{
		id: newItemID(),
		submittedAt: new Date("12/05/2025"),
		url: "https://itch.io/wizard-tower",
		title: "Wizard Tower Defense",
		by: "MagicHat",
		note: "Tiny game.",
		status: "queue",
		infoChangedAt: new Date(),
		statusChangedAt: new Date(),
	},
	{
		id: newItemID(),
		submittedAt: new Date("10/28/2025"),
		url: "https://itch.io/neon-racer",
		title: "Neon Racer Arcade",
		by: "GridBreaker",
		note: "Highly recommended by the 'Indie Gems' podcast as a fantastic example of a retro-style racer that nails the aesthetic and feel of classic arcade games. Good for a quick session.",
		status: "queue",
		infoChangedAt: new Date(),
		statusChangedAt: new Date(),
	},
	{
		id: newItemID(),
		submittedAt: new Date("10/05/2025"),
		url: "https://itch.io/deep-sea-diver",
		title: "Deep Sea Diver 3000",
		by: "AquaTek",
		note: "This game is reportedly incredibly challenging, focusing on resource management and permadeath in the deep ocean. I'll need a quiet afternoon to really dive into this one.",
		status: "queue",
		infoChangedAt: new Date(),
		statusChangedAt: new Date(),
	},
	{
		id: newItemID(),
		submittedAt: new Date("09/28/2025"),
		url: "https://itch.io/cryptid-photos",
		title: "Cryptid Photo Hunt",
		by: "ForestRyly",
		note: "Quick playthrough.",
		status: "queue",
		infoChangedAt: new Date(),
		statusChangedAt: new Date(),
	},
	{
		id: newItemID(),
		submittedAt: new Date("08/10/2025"),
		url: "https://itch.io/robot-pals",
		title: "Robot Pals: The Adventure",
		by: "FriendlyCode",
		note: "My friend **Ryly** suggested this one as a chill platformer.",
		status: "queue",
		infoChangedAt: new Date(),
		statusChangedAt: new Date(),
	},
	{
		id: newItemID(),
		submittedAt: new Date("11/29/2025"),
		url: "https://itch.io/submittedAt-loop-puzzle",
		title: "The Chronos Conundrum",
		by: "LoopGames",
		note: "Complex submittedAt-rewind puzzle game. Save it for a weekend when I can fully focus.",
		status: "queue",
		infoChangedAt: new Date(),
		statusChangedAt: new Date(),
	},
];
